name: Build EXE Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter packaging yt-dlp google-auth-oauthlib google-api-python-client google-auth-httplib2 pyinstaller

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg

    - name: Build with PyInstaller
      run: |
        mkdir bin
        cp ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }} bin/ffmpeg.exe
        pyinstaller --noconsole --onefile --add-data "credentials.json;." --add-data "bin;bin" yturldown.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Youtube-To-Drive-Software
        path: dist/yturldown.exe
